
CREATE DATABASE IF NOT EXISTS MyDataBase;

USE MyDataBase;
CREATE TABLE IF NOT EXISTS PRODUIT (
    Id INT(6) PRIMARY KEY,
    PNOM VARCHAR(50),
    COULEUR VARCHAR(50),
    POIDS VARCHAR(20),
    PRIX INT(5)
);

-- Q2. 
INSERT INTO PRODUIT (Id, PNOM, COULEUR, POIDS, PRIX) VALUES
(1, 'Produit1', 'Rouge', '3 Kg', 250),
(2, 'Produit2', 'Vert', '6 Kg', 400),
(3, 'Produit3', 'Bleu', '4 Kg', 350),
(4, 'Produit4', 'Jaune', '2 Kg', 200),
(5, 'Produit5', 'Noir', '5 Kg', 450),
(6, 'Produit6', 'Blanc', '1 Kg', 150);

-- Q3 
SELECT * FROM PRODUIT;

-- q4
SELECT * FROM PRODUIT WHERE PRIX > 300 ORDER BY PRIX;

-- Q5
SELECT PNOM, COULEUR FROM PRODUIT WHERE CAST(SUBSTRING(POIDS, 1, LENGTH(POIDS) - 2) AS DECIMAL) < 5 ORDER BY PRIX;


-- Q6. 
UPDATE PRODUIT SET PRIX = 320 WHERE Id = 3;

-- Q7 
DELETE FROM PRODUIT ORDER BY Id DESC LIMIT 1;

-- Q8
DROP TABLE IF EXISTS PRODUIT;




